### ISSUE TITLE
Classpath issues with local code for template evaluation

### ISSUE THREAD

**Issue by respatialized** [vivid-inc/ash-ra-template#2]
Hi! Thanks for this great library - I'm extremely excited about its capabilities, as it essentially brings the power and flexibility of the Clojure ecosystem to a concept very similar to Matthew Butterick's `pollen` library for Racket. However, I'm having some trouble getting my code across the edge of the sandbox that you're using `ShimDandy` to create.

The workflow I'm trying to support is: 
1. create helper functions around the capabilities of `hiccup`.
2. call those functions when rendering the templates into HTML files.

I'm encountering a lot of errors, depending on how I try the invocation - not least because I'm probably not super solid in my understanding of vars, symbols, and namespaces. Say I have some fns defined like the following:

```clojure
(ns user
  (:require [hiccup.core :refer [html]]
                [vivid.art :as art]))

(defn my-header [text] (html [:h1 text]))
(defn span [text] (html [:span text]))
(defn span2 [text] (str "<span>" text "</span>"))

(def sample-template
  "test 1: <%= (my-header \"sample text!\") %> 
   test 2: <%= (span \"sample span!\") %>
   test 3: <%= (span2 \"sample span 2\") %>")
```
Here are the various ways I've tried to get my functions into the runtime environment:

**Passing the function name directly to `art/render` throws a `IllegalStateException`:**
```clojure
(art/render sample-template
                 {:bindings '{my-header my-header span span span2 span2}})
> Execution error (IllegalStateException) at user/eval158 (REPL:11).
> Attempting to call unbound fn: #'user/my-header
```

**Quoting the function names in the `:bindings` map returns `null` for each invocation:**
```clojure
(art/render sample-template
                 {:bindings '{my-header 'my-header span 'span span2 'span2}})
> "test 1: null \n   test 2: null\n   test 3: null"
```

**Attempting to pass the fully-qualified function name (using `var` or `resolve`) causes a `StackOverflowError`** 
```clojure
(art/render sample-template
                  '{:bindings {my-header (var my-header) span  (var span) span2  (var span2) }})
> Execution error (StackOverflowError) at (REPL:1).
> null
```
I tried as best I could to replicate the example in `bindings-test.clj` - I'm not sure if I did it correctly, because I don't know which of these methods are supposed to be the canonical way of passing in these functions.

When that failed, I decided to try a different tack: factor out my rendering code into a library and add it as a local dependency using the capabilities of `tools.deps`.

```clojure
;; deps.edn:
{:paths ["build"]
 :deps {
  org.clojure/java.classpath {:mvn/version "1.0.0"}
  vivid/ash-ra-template {:mvn/version "0.4.0"}
  my-lib {:local/root  "/path/to/my-lib"}}}
```

```clojure
;; /path/to/my-lib/src/my-lib/render.clj
(ns my-lib.render
  (:require [hiccup.core :refer [html]]))

(defn em [text] (html [:em text]))
```

```clojure
(ns build
  (:require [vivid.art :as art]
            [clojure.java.io :as io]
            [my-lib.render :as render])

(def art-config
  {:dependencies
   {'hiccup {:mvn/version "2.0.0-alpha2"}
    'org.clojure/clojure {:mvn/version "1.10.0"}
    'my-lib {:local/root  "/path/to/my-lib"}
    'org.clojure/java.classpath {:mvn/version "1.0.0"}}})
```
**Local deps added with `:dependencies` throw a classpath exception when `(:require )`'d**

I know I'm referring to the classpath correctly because I can invoke the following shell command:
```bash
$ clj -Sdeps '{:deps {my-lib {:local/root "./my-lib"}}}' -e '(require `[my-lib.render :as render]) (my-lib.render/em "test")'
> "<em>help</em>"
```
I can also invoke the functions from my local library from the repl if I `(require)` them. However, here's what happens when I try to invoke them from within the `ash-ra-template` environment:
```clojure
(art/render "<% (require '[my-lib.render :refer [em]]) %><%= (em \"text\")"
                  {:dependencies {'my-lib {:local/root "./my-lib"}}})
>Execution error (FileNotFoundException) at user/eval156 (REPL:7).
>Could not locate Clojure resource on classpath: my-lib/render.clj
```
I did a sanity check by invoking some `hiccup` functions directly:
```clojure
(art/render "<% (require '[hiccup.core :refer [html]]) %><%= (html [:span \"text\"])"
                  {:dependencies {'hiccup {:mvn/version "2.0.0-alpha2"}}})
> "<span>text</span>"
```
So the `hiccup` fns work, but mine don't, even though the directories containing `render.clj` are on the classpath (I checked by using `clojure.java.classpath` within the template). 

Any idea on how I should proceed here? I could simply define all my rendering functions inline in my page templates, but that seems like it would rapidly become unmaintainable. I'm happy to provide additional info for debugging or clarify these examples - I tried to make them as reproducible as possible.

**Comment by vivid-inc** [comment]
Thanks for your kind words. When we were choosing a Lisp to marry ourselves to for the next phase of development, Racket was attractive in no small part due to Pollen. We chose Clojure because we were already well-rooted in the Java ecosystem. Specifically for static site generation, we elected to continue making do with Middleman while we eventually arrive at a state with ART and other tooling that allows us to somewhat converge on a single Clojure- and Java-based tool-chain for product and service development.

Work has begun on porting existing web content projects to this new tool-chain. Apropos to ART are:
- Bringing code and data into the template evaluation environment.
- A generalization of Middleman's layout behavior with ``yield`` for template nesting.
- Participating as one factor in a larger production pipeline. Others being SCSS -> CSS compilation, CLJS -> JS compilation, image optimization ...
This work will congeal as ART v0.5.0, with full examples involving usage of custom code within templates.

Seaguing into the subject of how to do bindings with the current ART v0.4.0 release: The documentation doesn't say this, but bindings only make it across the ShimDandy bridge into the template evaluation environment as values, where they are evaluated al a EDN. Function definitions, among other things, are not reconstituted via this mechanism.

As for how to do it, Please stand by -- whipping up a demo on a dedicated Git branch.

**Comment by vivid-inc** [comment]
A working sample is on the `gh-issue-2` branch.

The key change is to use `my-lib` as a `mvn/version` style dependency instead of `local/root`. This entails needing to install `my-lib` to your local Maven repo first. Putting it all together:

```bash
cd gh-issue-2/my-lib && lein install
cd ../require-deps
clojure -m require-deps
```

As for being able to utilize `local/root`, this will certainly be examined during v0.5.0.

**Comment by respatialized** [comment]
I just got everything working (with `cambada` and `deps-deploy` instead of `lein`) for a local workflow. Thanks very much for your guidance! Hope you're staying safe in these tumultuous COVID-19 times.

By the way, as someone who has spent a fair bit of [time thinking out loud](https://respatialized.net/not-a-tree.html) about the limitations of existing tools for programmers to put words on the internet, I'd be more than happy to write up a more coherent explanation of what `ash-ra-template` brings to the table. The tl;dr: everyone starts off with Markdown because it's "easy" and then proceeds to bolt symbolic computation and semantics back on to it in a completely ad-hoc way (the same story as YAML, incidentally).

**Comment by vivid-inc** [comment]
Pleased that it's working for you!

And yes, I'd love to read your article on `art`. You're right about the bolting-on as opposed to designing-in, the effects of which can be seen everywhere one cares to look. I recently read an explanation for bolting-on behavior phrased as "just keeping your head above water," which cast the phenomenon in an empathetic light for me. But it does nothing to address root causes... There are appropriate contexts for the safety provided by non-Turing systems, contexts for unbridled symbolic computation, and every other landing place on the spectrum. I think you're in a good position here, because Lisp offers boundless fertile ground for analysis and discussion.
